package com.tawajood.vetclinic.utils

object Constants {
    const val LANG = "lang"
    const val EN = "en"
    const val AR = "ar"
    const val IS_FIRST = "is_first"
    const val TOKEN = "token"
    const val FCM_TOKEN = "fcm_token"
    const val USER_ID = "user_id"
    const val USERNAME = "username"
    const val PHONE = "phone"
    const val COUNTRY_CODE = "country_code"
    const val USER_IMAGE = "user_image"
    const val IS_NOTIFIABLE = "user_image"
    const val EMAIL = "email"
    const val LAT = "lat"
    const val LNG = "lng"
    const val PARKING = "parking"
    const val SMS_TOKEN = "Bearer av9ZwgJyL-6SqEcFCWlS52gOEUgQ_50EcgtNMrfbaeY"
    const val _DATA = "_data"
    const val REG_BODY = "reg_body"
    const val VER_CODE = "ver_code"
    const val MSG = "msg"
    const val IMAGE = "image"
    const val CLINIC = "clinic"
    const val CLINIC_NAME = "name"
    const val REVIEW_CLINIC = "review"
    const val PET_ID = "id"
    const val CONSULTANT_ID = "id"
    const val CAT_ID = "id"
    const val VENDOR_ID = "id"
    const val SUB_CAT_ID = "id"
    const val PRODUCT_ID = "id"
    const val CART_COUNT = "c"
    const val OPEN_NOTIFICATION = "open_not"
    const val RECEIVER_ID = "receiver_id"
    const val ORDER_ID = "o"

}